version: '3.8'
services:
  backend:
    build: ./backend
    container_name: news_backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: news_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
